micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT10S
        descriptions: true
  server:
    port: 8081
  caches:
    headlines:
      maximumSize: 20
      charset: UTF-8
      heap:
        maximum-size: 200Mb

endpoints:
  prometheus:
    sensitive: false
